import Banners from "./components/banners";
import Filter from "./components/filter";
import Hamburger from "./components/hamburger";
import Header from "./components/header";
import ImgHoverCarousel from "./components/imgHoverCarousel";
import MatchHeight from "./components/matchHeight";
import Popups from "./components/popups";
import Product from "./components/product";
import ProductsSlider from "./components/productsSlider";
import QuickView from "./components/quickView";

new Banners();
new ProductsSlider();
new MatchHeight();
new Product();
new Popups();
new QuickView();
new Filter();
new Hamburger();
new Header();
new ImgHoverCarousel();
